import type { Metadata } from "next";
import React from "react";
import ClientLayout from "./ClientLayout";

export const metadata: Metadata = {
    title: "The One Piece",
    description: "Generated by create next app",
};

interface IRootLayout {
    children: React.ReactNode;
}

const RootLayout: React.FC<IRootLayout> = ({ children }) => {
    return (
        <html lang="fr">
            <body>
                <ClientLayout>{children}</ClientLayout>
            </body>
        </html>
    );
};

export default RootLayout;
