import type { Metadata } from "next";
import React from "react";
import ClientLayout from "./ClientLayout";

export const metadata: Metadata = {
    title: "The One Piece",
<<<<<<< HEAD
    description: "The One Piece est une application destinée à partager l'univers du manga One Piece aux plus grands nombres. ",
=======
    description: "Generated by create next app",
>>>>>>> f1994565b32afe4b3f135725c7e91c004995447d
};

interface IRootLayout {
    children: React.ReactNode;
}

const RootLayout: React.FC<IRootLayout> = ({ children }) => {
    return (
        <html lang="fr">
<<<<<<< HEAD
            <head>
                <link rel="icon" href="images/favicon.ico" />
            </head>
=======
>>>>>>> f1994565b32afe4b3f135725c7e91c004995447d
            <body>
                <ClientLayout>{children}</ClientLayout>
            </body>
        </html>
    );
};

export default RootLayout;
